export const PORTFOLIO_TICKER_OPTIONS = [
  { value: 'SPY', label: 'SPY - S&P 500' },
  { value: 'QQQ', label: 'QQQ - NASDAQ 100' },
  { value: 'DIA', label: 'DIA - Dow Jones Industrial Average' },
  { value: 'IWM', label: 'IWM - Russell 2000' },
  { value: '^IBEX', label: '^IBEX - IBEX 35 (EUR)' },
  { value: '^STOXX50E', label: '^STOXX50E - Euro Stoxx 50 (EUR)' },
  { value: '^N225', label: '^N225 - Nikkei 225 (JPY)' },
  { value: '^990100-USD-STRD', label: '^990100-USD-STRD - MSCI World (USD)' },

];

export const MACRO_FACTOR_DESCRIPTIONS = {
  'GSPC': 'S&P 500: Main US stock market index',
  'SP500': 'S&P 500: Main US stock market index',
  'VIX': 'Volatility Index: Measures market fear',
  'VXN': 'NASDAQ Volatility',
  'TLT': 'US Treasury Bonds 20-year',
  'GOVT_20Y': 'US Treasury Bonds 20-year',
  'HYG': 'High Yield: High-risk, high-return corporate bonds',
  'LQD': 'Investment Grade: High-quality corporate bonds',
  'JNK': 'High Yield: Junk bonds',
  'IBND': 'International Corporate Bonds',
  'EUR_BOND': 'International Corporate Bonds',
  'DBJP': 'Japan Bonds',
  'JPN_BOND': 'Japan Bonds',
  'GER_BOND': 'Germany Bonds',
  'BUNL': 'Germany Bonds',
  'TNX': 'Treasury Yield 10-year',
  'RATE_10Y': 'Treasury Yield 10-year',
  'TYX': 'Treasury Yield 30-year',
  'RATE_30Y': 'Treasury Yield 30-year',
  'IRX': 'Treasury Yield 3-month',
  'RATE_2Y': 'Treasury Yield 2-year',
  'RATE_3M': 'Treasury Yield 3-month',
  'DX-Y.NYB': 'Dollar Index (DXY): Dollar strength vs other currencies',
  'DXY': 'Dollar Index: Dollar strength vs other currencies',
  'CL=F': 'WTI Crude Oil',
  'OIL': 'WTI Crude Oil',
  'GC=F': 'Gold: Safe haven asset',
  'GOLD': 'Gold: Safe haven asset',
  'HG=F': 'Copper: Economic growth indicator',
  'COPPER': 'Copper: Economic growth indicator',
  'FVX': 'Treasury Yield 5-year',
  'RATE_5Y': 'Treasury Yield 5-year',
  'EURUSD=X': 'EUR/USD Exchange Rate',
  'EUR_USD': 'EUR/USD Exchange Rate',
  'GDAXI': 'German DAX Index',
  'DAX': 'German DAX Index',
  'N225': 'Nikkei 225: Japan stock market index',
  'NIKKEI': 'Nikkei 225: Japan stock market index',
  'SI=F': 'Silver Futures',
  'SILVER': 'Silver Futures',
};

export const getFactorDescription = (factor) => {
  const cleanFactor = factor.replace(/^\^/, '');
  return MACRO_FACTOR_DESCRIPTIONS[cleanFactor] || MACRO_FACTOR_DESCRIPTIONS[factor] || 'Macroeconomic factor';
};

export const MACRO_FACTORS_OPTIONS = [
  { value: 'VIX', ticker: '^VIX', label: 'VIX - Volatility Index' },
  { value: 'RATE_3M', ticker: '^IRX', label: 'RATE_3M - Treasury 3-Month' },
  { value: 'RATE_2Y', ticker: 'FRED:DGS2', label: 'RATE_2Y - Treasury 2-Year (FRED)' },
  { value: 'RATE_5Y', ticker: '^FVX', label: 'RATE_5Y - Treasury 5-Year' },
  { value: 'RATE_10Y', ticker: '^TNX', label: 'RATE_10Y - Treasury 10-Year' },
  { value: 'RATE_30Y', ticker: '^TYX', label: 'RATE_30Y - Treasury 30-Year' },
  { value: 'GOVT_20Y', ticker: 'TLT', label: 'GOVT_20Y - Treasury Bond 20Y+ (TLT)' },
  { value: 'HYG', ticker: 'HYG', label: 'HYG - High Yield Corporate' },
  { value: 'LQD', ticker: 'LQD', label: 'LQD - Investment Grade Corporate' },
  { value: 'DXY', ticker: 'DX-Y.NYB', label: 'DXY - Dollar Index' },
  { value: 'EUR_USD', ticker: 'EURUSD=X', label: 'EUR/USD' },
  { value: 'GOLD', ticker: 'GC=F', label: 'GOLD - Gold Futures' },
  { value: 'OIL', ticker: 'CL=F', label: 'OIL - Crude Oil WTI' },
  { value: 'COPPER', ticker: 'HG=F', label: 'COPPER - Copper Futures' },
  { value: 'SILVER', ticker: 'SI=F', label: 'SILVER - Silver Futures' },
  { value: 'SP500', ticker: '^GSPC', label: 'SP500 - S&P 500' },
  { value: 'NIKKEI', ticker: '^N225', label: 'NIKKEI - Nikkei 225' },
  { value: 'DAX', ticker: '^GDAXI', label: 'DAX - German DAX' },
  { value: 'JPN_BOND', ticker: 'DBJP', label: 'JPN_BOND - Japan Bond ETF' },
  { value: 'EUR_BOND', ticker: 'IBND', label: 'EUR_BOND - Europe Bond ETF' },
  { value: 'GER_BOND', ticker: 'BUNL', label: 'GER_BOND - Germany Bond ETF' },
];

export const SITUATION_AUTO_FACTORS = [
  'RATE_3M', 'RATE_2Y', 'RATE_5Y', 'RATE_10Y', 'RATE_30Y',
  'GOVT_20Y', 'HYG', 'LQD',
  'VIX', 'DXY', 'EUR_USD',
  'GOLD', 'OIL', 'COPPER', 'SILVER',
  'SP500', 'NIKKEI', 'DAX',
  'JPN_BOND', 'EUR_BOND',
];
