export const PORTFOLIO_TICKER_OPTIONS = [
  { value: '^GSPC', label: '^GSPC - S&P 500 Index (USD)' },
  { value: '^IXIC', label: '^IXIC - Nasdaq Composite Index (USD)' },
  { value: '^DJI', label: '^DJI - Dow Jones Industrial Average Index (USD)' },
  { value: '^RUA', label: '^RUA - Russell 3000 Index (USD)' },
  { value: '^IBEX', label: '^IBEX - IBEX 35 Index (EUR)' },
  { value: '^STOXX50E', label: '^STOXX50E - Euro Stoxx 50 Index (EUR)' },
  { value: '^N225', label: '^N225 - Nikkei 225 Index (JPY)' },
  { value: '^990100-USD-STRD', label: '^990100-USD-STRD - MSCI World Index (USD)' },
  { value: '000001.SS', label: '000001.SS - Shanghai Composite Index (CNY)' },
];

export const CAPM_BENCHMARK_SELECT_OPTIONS = [
  { value: '', label: 'Select benchmark...', disabled: true },
  ...PORTFOLIO_TICKER_OPTIONS,
];

export {
  MACRO_FACTOR_DEFINITIONS,
  MACRO_FACTORS_OPTIONS,
  MACRO_FACTORS_OPTIONS_GROUPED,
  MACRO_FACTOR_DESCRIPTIONS,
  getFactorDescription,
  normalizeFactorId,
  getFactorMetadata,
  getFactorCategory,
  macro_factors_primary,
  market_benchmarks,
  risk_proxies,
  SITUATION_AUTO_FACTORS,
  SITUATION_AUTO_FACTORS_CORE,
  SITUATION_AUTO_FACTORS_EXTENDED,
  SITUATION_YIELD_CURVE_FACTORS,
  SITUATION_GLOBAL_BOND_FACTORS,
  SITUATION_CREDIT_LIQUIDITY_FACTORS,
  SITUATION_INFLATION_STRIP,
  SITUATION_INFLATION_STRIP_FULL,
  extractPriceForFactorFromRow,
  mergeMacroFactorPayloads,
  payloadHasTickerSeries,
  DERIVED_FACTOR_SPECS,
  listFactorsByFilter,
  groupFactorsByFamily,
  formatFactorCategoryLabel,
  FACTOR_CATEGORY_LABEL_ES,
} from './macroFactorRegistry';
